solve error on deleting operation: Error deleting: TypeError: s.indexOf is not a function at..., solve it by changeing the do id name to prevent the conflict